name: Deployment
on:
  push:
    branches:
      - dev
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Packages
      run: npm install
    - name: Lead Pics Optimize
      uses: sharadcodes/img-resizer@v1.1
      with:
        image-folder: "public/leads"
        new-resolution: '300x300'
        output-folder: "public/leads"
    - name: Chapter Pics Optimize
      uses: sharadcodes/img-resizer@v1.1
      with:
        image-folder: "public/chapters"
        new-resolution: '500x500'
        output-folder: "public/chapters"
    - name: Build
      run: npm run build
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_dir: ./build
        publish_branch: master 
